### PR TITLE
13.0 [1814][ADD] base_company_reporting

### PR DESCRIPTION
**Pull request by TomohiroAbe-Quartile**
[1814](https://www.quartile.co/web?debug=1#id=1814&action=771&model=project.task&view_type=form&menu_id=505)

https://github.com/qrtl/psc-custom/pull/3
https://github.com/qrtl/psc-custom/pull/5

### CODE REVIEW

**Comment by TomohiroAbe-Quartile** [comment]
Sorry, I forgot squash.
I compared st1 and this branch, confirmed nothing to different.

**Comment by TomohiroAbe-Quartile** [comment]
Please ignore pre-commit failed, this is caused by report_csv.

**Review by yostashiro — APPROVED** [review]
👍

**Review by yostashiro — CHANGES_REQUESTED** [review]
@TomohiroAbe-Quartile Sorry, can you please remove sales_team_attribute from this PR. https://github.com/qrtl/psc-custom/pull/4 shouldn't go to the production if the customer doesn't use it.

**Comment by TomohiroAbe-Quartile** [comment]
@yostashiro 
I reverted pull/4 and commit it.(https://github.com/qrtl/psc-custom/pull/6/commits/0cfe5ddbc60d7f5ed8b1710dca9417efbbfc00d9)

**Review by yostashiro — APPROVED** [review]
👍

**Pull request merged**
